In [13]:
import pandas as pd
import numpy as np

df = pd.read_csv("synthetic_telemetry_data.csv")

print("Dataset Shape:", df.shape)
print("\nFirst 5 Rows:")
display(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nTotal Missing Values:", df.isnull().sum().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

print("\nUnique Values:")
print(df.nunique())

print("\nBasic Statistics:")
display(df.describe().T)

print("\nObject/Categorical Columns:")
print(df.select_dtypes(include=["object"]).columns.tolist())

print("\nNumerical Columns:")
print(df.select_dtypes(include=[np.number]).columns.tolist())

Dataset Shape: (1970, 41)

First 5 Rows:

,vehicle_id,brand,timestamp,odometer_reading,engine_temp_c,engine_rpm,oil_pressure_psi,coolant_temp_c,fuel_level_percent,fuel_consumption_lph,...,vehicle_speed_kph,ambient_temp_c,humidity_percent,gps_latitude,gps_longitude,engine_failure_imminent,brake_issue_imminent,battery_issue_imminent,failure_date,failure_type
0,VEH0000,BMW,2023-01-01 00:00:00,31381.561743,99.388213,2212.155243,55.522505,91.788105,68.368162,4.076315,...,116.501239,24.187057,83.785796,31.986296,78.203395,0,0,0,2050-01-01 00:00:00,No Failure
1,VEH0000,BMW,2023-01-01 00:56:00,31391.284155,84.118706,961.795251,57.799346,87.283282,99.064394,7.059168,...,39.409933,15.148875,57.418501,30.620539,84.389727,0,0,0,2050-01-01 00:00:00,No Failure
2,VEH0000,BMW,2023-01-01 01:28:00,31428.088015,103.521431,742.050437,50.398848,83.503155,80.280244,10.792362,...,82.077798,23.138714,80.540135,30.634997,79.039234,0,0,0,2050-01-01 00:00:00,No Failure
3,VEH0000,BMW,2023-01-01 01:27:00,31463.271669,91.130527,2723.042461,41.719715,90.997963,13.892586,1.564630,...,70.294428,35.058947,57.221563,33.490971,76.107248,0,0,0,2050-01-01 00:00:00,No Failure
4,VEH0000,BMW,2023-01-01 01:00:00,31490.411858,96.887263,2647.979969,38.438964,93.029011,20.871931,6.814662,...,74.028392,18.024207,47.680115,28.392300,83.160007,0,0,0,2050-01-01 00:00:00,No Failure

Missing Values:
vehicle_id                 0
brand                      0
timestamp                  0
odometer_reading           0
engine_temp_c              0
engine_rpm                 0
oil_pressure_psi           0
coolant_temp_c             0
fuel_level_percent         0
fuel_consumption_lph       0
engine_load_percent        0
throttle_pos_percent       0
air_flow_rate_gps          0
exhaust_gas_temp_c         0
vibration_level            0
engine_hours               0
brake_fluid_level_psi      0
brake_pad_wear_mm          0
brake_temp_c               0
abs_fault_indicator        0
brake_pedal_pos_percent    0
wheel_speed_fl_kph         0
wheel_speed_fr_kph         0
wheel_speed_rl_kph         0
wheel_speed_rr_kph         0
battery_voltage_v          0
battery_current_a          0
battery_temp_c             0
alternator_output_v        0
battery_charge_percent     0
battery_health_percent     0
vehicle_speed_kph          0
ambient_temp_c             0
humidity_percent           0
gps_latitude               0
gps_longitude              0
engine_failure_imminent    0
brake_issue_imminent       0
battery_issue_imminent     0
failure_date               0
failure_type               0
dtype: int64

Total Missing Values: 0

Duplicate Rows: 0

Data Types:
vehicle_id                  object
brand                       object
timestamp                   object
odometer_reading           float64
engine_temp_c              float64
engine_rpm                 float64
oil_pressure_psi           float64
coolant_temp_c             float64
fuel_level_percent         float64
fuel_consumption_lph       float64
engine_load_percent        float64
throttle_pos_percent       float64
air_flow_rate_gps          float64
exhaust_gas_temp_c         float64
vibration_level            float64
engine_hours               float64
brake_fluid_level_psi      float64
brake_pad_wear_mm          float64
brake_temp_c               float64
abs_fault_indicator          int64
brake_pedal_pos_percent    float64
wheel_speed_fl_kph         float64
wheel_speed_fr_kph         float64
wheel_speed_rl_kph         float64
wheel_speed_rr_kph         float64
battery_voltage_v          float64
battery_current_a          float64
battery_temp_c             float64
alternator_output_v        float64
battery_charge_percent     float64
battery_health_percent     float64
vehicle_speed_kph          float64
ambient_temp_c             float64
humidity_percent           float64
gps_latitude               float64
gps_longitude              float64
engine_failure_imminent      int64
brake_issue_imminent         int64
battery_issue_imminent       int64
failure_date                object
failure_type                object
dtype: object

Unique Values:
vehicle_id                   50
brand                        10
timestamp                   701
odometer_reading           1970
engine_temp_c              1970
engine_rpm                 1861
oil_pressure_psi           1970
coolant_temp_c             1970
fuel_level_percent         1970
fuel_consumption_lph       1865
engine_load_percent        1926
throttle_pos_percent       1846
air_flow_rate_gps          1953
exhaust_gas_temp_c         1970
vibration_level            1970
engine_hours               1970
brake_fluid_level_psi      1970
brake_pad_wear_mm          1970
brake_temp_c               1970
abs_fault_indicator           2
brake_pedal_pos_percent    1970
wheel_speed_fl_kph         1970
wheel_speed_fr_kph         1970
wheel_speed_rl_kph         1970
wheel_speed_rr_kph         1970
battery_voltage_v          1970
battery_current_a          1970
battery_temp_c             1970
alternator_output_v        1970
battery_charge_percent     1970
battery_health_percent     1970
vehicle_speed_kph          1893
ambient_temp_c             1970
humidity_percent           1970
gps_latitude               1970
gps_longitude              1970
engine_failure_imminent       2
brake_issue_imminent          2
battery_issue_imminent        2
failure_date                 36
failure_type                 10
dtype: int64

Basic Statistics:

,count,mean,std,min,25%,50%,75%,max
odometer_reading,1970.0,55805.596064,25276.174846,13578.948264,34537.434560,56545.906171,77938.260730,100409.771733
engine_temp_c,1970.0,95.098185,5.201481,77.781925,91.593183,95.084360,98.620236,119.322471
engine_rpm,1970.0,2011.461245,760.883948,700.000000,1457.167122,1998.276722,2535.801415,4167.823670
oil_pressure_psi,1970.0,44.705878,10.115871,5.928049,37.687975,45.024308,51.481993,80.267052
coolant_temp_c,1970.0,89.874554,2.985144,78.797191,87.853215,89.767156,91.926039,100.659740
fuel_level_percent,1970.0,47.998493,29.182622,0.166009,22.081471,47.287384,73.024963,99.997479
fuel_consumption_lph,1970.0,5.123180,2.919474,0.000000,2.990431,5.052483,7.132336,15.127696
engine_load_percent,1970.0,39.999500,19.273029,0.000000,26.540634,39.383741,53.384306,100.000000
throttle_pos_percent,1970.0,29.981324,18.799032,0.000000,16.268606,28.781407,42.784640,91.815640
air_flow_rate_gps,1970.0,50.292807,19.670713,0.000000,36.972980,50.179637,64.408787,106.856022
exhaust_gas_temp_c,1970.0,407.523815,154.496574,-70.396559,300.185452,400.748136,511.885278,1040.326993
vibration_level,1970.0,1.512282,0.555870,-0.004329,1.162228,1.493116,1.837397,7.432883
engine_hours,1970.0,2614.534129,1315.287739,503.457575,1523.095501,2580.719026,3854.647827,4957.240678
brake_fluid_level_psi,1970.0,997.507364,105.224517,430.532343,932.708160,999.740127,1065.744598,1314.860365
brake_pad_wear_mm,1970.0,8.071069,1.010322,5.909885,7.373013,7.957371,8.974693,9.796315
brake_temp_c,1970.0,81.608507,54.587915,-84.880838,45.620817,79.018173,114.700986,399.355360
abs_fault_indicator,1970.0,0.111675,0.315046,0.000000,0.000000,0.000000,0.000000,1.000000
brake_pedal_pos_percent,1970.0,49.997193,28.694617,0.157694,24.366309,50.282756,74.829909,99.964109
wheel_speed_fl_kph,1970.0,60.655521,30.338577,-35.553986,40.241667,60.996021,81.511203,154.368619
wheel_speed_fr_kph,1970.0,59.565926,31.196927,-56.399755,38.318009,60.058585,80.561002,171.472700
wheel_speed_rl_kph,1970.0,60.530240,30.099707,-55.132765,40.022750,60.103713,81.847206,175.505929
wheel_speed_rr_kph,1970.0,60.083571,30.272161,-42.231741,39.548633,60.502644,80.145359,160.179239
battery_voltage_v,1970.0,12.578856,0.531746,9.065082,12.266905,12.595619,12.928926,14.524733
battery_current_a,1970.0,10.090152,21.207427,-67.829694,-3.473606,10.737516,24.296475,83.362796
battery_temp_c,1970.0,25.003929,5.098852,6.669371,21.494980,25.002662,28.411607,42.367341
alternator_output_v,1970.0,14.197447,0.292889,13.110096,14.007229,14.206000,14.394783,15.241447
battery_charge_percent,1970.0,70.092167,17.161083,40.018290,55.096188,70.652447,84.273524,99.968430
battery_health_percent,1970.0,94.329009,2.541468,90.162163,91.960024,94.172950,96.249211,99.386264
vehicle_speed_kph,1970.0,70.201288,38.185877,0.000000,42.645593,69.336619,96.188556,180.000000
ambient_temp_c,1970.0,29.966583,9.867784,-17.116179,23.609246,30.271354,36.709522,63.348462
humidity_percent,1970.0,59.783230,14.721301,9.914752,50.103555,59.574084,69.550834,117.766913
gps_latitude,1970.0,31.492223,1.988963,28.000396,29.787474,31.509410,33.181098,34.997221
gps_longitude,1970.0,80.016424,2.937999,75.002955,77.373052,80.009871,82.629875,84.997696
engine_failure_imminent,1970.0,0.003553,0.059519,0.000000,0.000000,0.000000,0.000000,1.000000
brake_issue_imminent,1970.0,0.008122,0.089777,0.000000,0.000000,0.000000,0.000000,1.000000
battery_issue_imminent,1970.0,0.006091,0.077829,0.000000,0.000000,0.000000,0.000000,1.000000

Object/Categorical Columns:
['vehicle_id', 'brand', 'timestamp', 'failure_date', 'failure_type']

Numerical Columns:
['odometer_reading', 'engine_temp_c', 'engine_rpm', 'oil_pressure_psi', 'coolant_temp_c', 'fuel_level_percent', 'fuel_consumption_lph', 'engine_load_percent', 'throttle_pos_percent', 'air_flow_rate_gps', 'exhaust_gas_temp_c', 'vibration_level', 'engine_hours', 'brake_fluid_level_psi', 'brake_pad_wear_mm', 'brake_temp_c', 'abs_fault_indicator', 'brake_pedal_pos_percent', 'wheel_speed_fl_kph', 'wheel_speed_fr_kph', 'wheel_speed_rl_kph', 'wheel_speed_rr_kph', 'battery_voltage_v', 'battery_current_a', 'battery_temp_c', 'alternator_output_v', 'battery_charge_percent', 'battery_health_percent', 'vehicle_speed_kph', 'ambient_temp_c', 'humidity_percent', 'gps_latitude', 'gps_longitude', 'engine_failure_imminent', 'brake_issue_imminent', 'battery_issue_imminent']

In [14]:
df["timestamp"] = pd.to_datetime(df["timestamp"])
df["failure_date"] = pd.to_datetime(df["failure_date"])

df["breakdown_within_30days"] = (
    (df["failure_date"] >= df["timestamp"]) &
    (df["failure_date"] <= df["timestamp"] + pd.Timedelta(days=30))
).astype(int)

print("Target Distribution:")
print(df["breakdown_within_30days"].value_counts())

print("\nTarget Percentage:")
print(
    df["breakdown_within_30days"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Target Distribution:
breakdown_within_30days
0    1935
1      35
Name: count, dtype: int64

Target Percentage:
breakdown_within_30days
0    98.22
1     1.78
Name: proportion, dtype: float64

In [15]:
drop_cols = [
    "failure_date",
    "failure_type",
    "engine_failure_imminent",
    "brake_issue_imminent",
    "battery_issue_imminent",
    "timestamp",
    "vehicle_id"
]

df_model = df.drop(columns=drop_cols)

print("Original shape:", df.shape)
print("Modeling shape:", df_model.shape)
print("\nRemaining columns:")
print(df_model.columns.tolist())

Original shape: (1970, 42)
Modeling shape: (1970, 35)

Remaining columns:
['brand', 'odometer_reading', 'engine_temp_c', 'engine_rpm', 'oil_pressure_psi', 'coolant_temp_c', 'fuel_level_percent', 'fuel_consumption_lph', 'engine_load_percent', 'throttle_pos_percent', 'air_flow_rate_gps', 'exhaust_gas_temp_c', 'vibration_level', 'engine_hours', 'brake_fluid_level_psi', 'brake_pad_wear_mm', 'brake_temp_c', 'abs_fault_indicator', 'brake_pedal_pos_percent', 'wheel_speed_fl_kph', 'wheel_speed_fr_kph', 'wheel_speed_rl_kph', 'wheel_speed_rr_kph', 'battery_voltage_v', 'battery_current_a', 'battery_temp_c', 'alternator_output_v', 'battery_charge_percent', 'battery_health_percent', 'vehicle_speed_kph', 'ambient_temp_c', 'humidity_percent', 'gps_latitude', 'gps_longitude', 'breakdown_within_30days']

In [16]:

X = df_model.drop("breakdown_within_30days", axis=1)
y = df_model["breakdown_within_30days"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

Features shape: (1970, 34)
Target shape: (1970,)

Target distribution:
breakdown_within_30days
0    1935
1      35
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Training data: (1576, 34)
Testing data: (394, 34)

Training target distribution:
breakdown_within_30days
0    1548
1      28
Name: count, dtype: int64

Testing target distribution:
breakdown_within_30days
0    387
1      7
Name: count, dtype: int64

In [18]:
# Numerical columns
numeric_cols = X_train.select_dtypes(include=np.number).columns

# Calculate IQR-based outliers
Q1 = X_train[numeric_cols].quantile(0.25)
Q3 = X_train[numeric_cols].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_counts = (
    ((X_train[numeric_cols] < lower_bound) |
     (X_train[numeric_cols] > upper_bound))
    .sum()
    .sort_values(ascending=False)
)

print("Outlier count per feature:")
print(outlier_counts)

print("\nTotal outlier values:")
print(outlier_counts.sum())

Outlier count per feature:
abs_fault_indicator        186
battery_voltage_v           31
brake_fluid_level_psi       21
brake_temp_c                20
battery_current_a           18
vibration_level             16
alternator_output_v         15
oil_pressure_psi            15
wheel_speed_fr_kph          15
humidity_percent            14
engine_temp_c               14
coolant_temp_c              12
ambient_temp_c              12
vehicle_speed_kph           12
wheel_speed_fl_kph          11
wheel_speed_rr_kph          10
throttle_pos_percent         8
wheel_speed_rl_kph           8
battery_temp_c               7
engine_load_percent          7
exhaust_gas_temp_c           6
fuel_consumption_lph         2
engine_rpm                   1
air_flow_rate_gps            1
odometer_reading             0
brake_pad_wear_mm            0
engine_hours                 0
fuel_level_percent           0
brake_pedal_pos_percent      0
battery_health_percent       0
battery_charge_percent       0
gps_latitude                 0
gps_longitude                0
dtype: int64

Total outlier values:
462

In [19]:
# Separate continuous numerical features from binary features
continuous_cols = [
    col for col in X_train.select_dtypes(include=np.number).columns
    if X_train[col].nunique() > 2
]

# Calculate IQR from training data only
Q1 = X_train[continuous_cols].quantile(0.25)
Q3 = X_train[continuous_cols].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Cap outliers in training data
X_train = X_train.copy()
X_test = X_test.copy()

for col in continuous_cols:
    X_train[col] = X_train[col].clip(
        lower=lower_bound[col],
        upper=upper_bound[col]
    )

    X_test[col] = X_test[col].clip(
        lower=lower_bound[col],
        upper=upper_bound[col]
    )

print("Outlier handling completed.")
print("Continuous features processed:", len(continuous_cols))
print("Binary features preserved:", 
      len(X_train.select_dtypes(include=np.number).columns) - len(continuous_cols))

Outlier handling completed.
Continuous features processed: 32
Binary features preserved: 1

In [20]:
categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()
numerical_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()

print("Categorical features:")
print(categorical_cols)

print("\nNumerical features:")
print(numerical_cols)

Categorical features:
['brand']

Numerical features:
['odometer_reading', 'engine_temp_c', 'engine_rpm', 'oil_pressure_psi', 'coolant_temp_c', 'fuel_level_percent', 'fuel_consumption_lph', 'engine_load_percent', 'throttle_pos_percent', 'air_flow_rate_gps', 'exhaust_gas_temp_c', 'vibration_level', 'engine_hours', 'brake_fluid_level_psi', 'brake_pad_wear_mm', 'brake_temp_c', 'abs_fault_indicator', 'brake_pedal_pos_percent', 'wheel_speed_fl_kph', 'wheel_speed_fr_kph', 'wheel_speed_rl_kph', 'wheel_speed_rr_kph', 'battery_voltage_v', 'battery_current_a', 'battery_temp_c', 'alternator_output_v', 'battery_charge_percent', 'battery_health_percent', 'vehicle_speed_kph', 'ambient_temp_c', 'humidity_percent', 'gps_latitude', 'gps_longitude']

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ]
)

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Processed training shape:", X_train_processed.shape)
print("Processed testing shape:", X_test_processed.shape)

Processed training shape: (1576, 43)
Processed testing shape: (394, 43)

In [22]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(
    class_weight="balanced",
    max_iter=2000,
    random_state=42
)

logistic_model.fit(X_train_processed, y_train)

print("Logistic Regression trained successfully.")

Logistic Regression trained successfully.

In [23]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score

)

y_prob_lr = logistic_model.predict_proba(X_test_processed)[:, 1]

y_pred_lr = (y_prob_lr >= 0.5).astype(int)

print("Classification Report:")
print(
    classification_report(
        y_test,
        y_pred_lr,
        target_names=["No Breakdown", "Breakdown"],
        zero_division=0
    )
)

print("ROC-AUC:", round(roc_auc_score(y_test, y_prob_lr), 4))
print("PR-AUC:", round(average_precision_score(y_test, y_prob_lr), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

Classification Report:
              precision    recall  f1-score   support

No Breakdown       0.99      0.94      0.97       387
   Breakdown       0.15      0.57      0.24         7

    accuracy                           0.93       394
   macro avg       0.57      0.76      0.60       394
weighted avg       0.98      0.93      0.95       394

ROC-AUC: 0.9365
PR-AUC: 0.3509

Confusion Matrix:
[[364  23]
 [  3   4]]

In [24]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression

class_weights = [
    {0: 1, 1: 5},
    {0: 1, 1: 10},
    {0: 1, 1: 20},
    {0: 1, 1: 30},
    {0: 1, 1: 40},
    {0: 1, 1: 50},
    "balanced"
]

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

results = []

for weight in class_weights:

    model = LogisticRegression(
        class_weight=weight,
        max_iter=2000,
        random_state=42
    )

    scores = cross_val_score(
        model,
        X_train_processed,
        y_train,
        cv=cv,
        scoring="average_precision"
    )

    results.append({
        "class_weight": str(weight),
        "mean_PR_AUC": scores.mean(),
        "std_PR_AUC": scores.std()
    })

weight_results = pd.DataFrame(results)

print(weight_results.sort_values(
    "mean_PR_AUC",
    ascending=False
))

    class_weight  mean_PR_AUC  std_PR_AUC
0   {0: 1, 1: 5}     0.291447    0.172561
6       balanced     0.287834    0.151557
4  {0: 1, 1: 40}     0.285613    0.151731
3  {0: 1, 1: 30}     0.282982    0.152702
5  {0: 1, 1: 50}     0.281969    0.153982
1  {0: 1, 1: 10}     0.281614    0.159035
2  {0: 1, 1: 20}     0.281415    0.150584

In [25]:
best_class_weight = {0: 1, 1: 5}

tuned_lr = LogisticRegression(
    class_weight=best_class_weight,
    max_iter=2000,
    random_state=42
)

tuned_lr.fit(X_train_processed, y_train)

print("Tuned Logistic Regression trained.")
print("Class weight:", best_class_weight)

Tuned Logistic Regression trained.
Class weight: {0: 1, 1: 5}

In [26]:

y_prob = tuned_lr.predict_proba(X_test_processed)[:, 1]

print("First 10 predicted probabilities:")
print(y_prob[:10])

First 10 predicted probabilities:
[1.93185277e-05 1.88229764e-02 4.80181774e-04 5.67443840e-06
 8.31290473e-02 2.91432141e-01 2.04904034e-04 4.04374592e-05
 7.49655496e-05 2.49107656e-05]

In [27]:
from sklearn.metrics import precision_score, recall_score, f1_score

threshold_results = []

for threshold in np.arange(0.05, 0.96, 0.05):

    y_pred = (y_prob >= threshold).astype(int)

    threshold_results.append({
        "Threshold": round(threshold, 2),
        "Precision": round(
            precision_score(y_test, y_pred, zero_division=0), 4
        ),
        "Recall": round(
            recall_score(y_test, y_pred, zero_division=0), 4
        ),
        "F1": round(
            f1_score(y_test, y_pred, zero_division=0), 4
        )
    })

threshold_df = pd.DataFrame(threshold_results)

display(threshold_df)

    Threshold  Precision  Recall      F1
0        0.05     0.1087  0.7143  0.1887
1        0.10     0.1282  0.7143  0.2174
2        0.15     0.1212  0.5714  0.2000
3        0.20     0.1600  0.5714  0.2500
4        0.25     0.1500  0.4286  0.2222
5        0.30     0.1765  0.4286  0.2500
6        0.35     0.2143  0.4286  0.2857
7        0.40     0.1818  0.2857  0.2222
8        0.45     0.2222  0.2857  0.2500
9        0.50     0.3333  0.2857  0.3077
10       0.55     0.3333  0.2857  0.3077
11       0.60     0.4000  0.2857  0.3333
12       0.65     0.2500  0.1429  0.1818
13       0.70     0.2500  0.1429  0.1818
14       0.75     0.3333  0.1429  0.2000
15       0.80     0.3333  0.1429  0.2000
16       0.85     0.5000  0.1429  0.2222
17       0.90     0.5000  0.1429  0.2222
18       0.95     0.5000  0.1429  0.2222

In [28]:
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import precision_score, recall_score, f1_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

cv_prob = cross_val_predict(
    tuned_lr,
    X_train_processed,
    y_train,
    cv=cv,
    method="predict_proba"
)[:, 1]

threshold_results = []

for threshold in np.arange(0.05, 0.96, 0.05):

    y_pred = (cv_prob >= threshold).astype(int)

    threshold_results.append({
        "Threshold": round(threshold, 2),
        "Precision": round(
            precision_score(y_train, y_pred, zero_division=0), 4
        ),
        "Recall": round(
            recall_score(y_train, y_pred, zero_division=0), 4
        ),
        "F1": round(
            f1_score(y_train, y_pred, zero_division=0), 4
        )
    })

threshold_df = pd.DataFrame(threshold_results)

display(
    threshold_df.sort_values(
        "F1",
        ascending=False
    )
)

    Threshold  Precision  Recall      F1
9        0.50     0.2955  0.4643  0.3611
8        0.45     0.2889  0.4643  0.3562
10       0.55     0.2927  0.4286  0.3478
7        0.40     0.2766  0.4643  0.3467
6        0.35     0.2500  0.4643  0.3250
11       0.60     0.2750  0.3929  0.3235
5        0.30     0.2364  0.4643  0.3133
4        0.25     0.2097  0.4643  0.2889
12       0.65     0.2500  0.3214  0.2812
13       0.70     0.2667  0.2857  0.2759
14       0.75     0.3043  0.2500  0.2745
3        0.20     0.1912  0.4643  0.2708
2        0.15     0.1807  0.5357  0.2703
1        0.10     0.1569  0.5714  0.2462
15       0.80     0.2857  0.2143  0.2449
17       0.90     0.3333  0.1786  0.2326
16       0.85     0.2941  0.1786  0.2222
0        0.05     0.1319  0.6786  0.2209
18       0.95     0.3636  0.1429  0.2051

In [29]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

best_threshold = 0.50

y_pred_final = (y_prob >= best_threshold).astype(int)

print("Final Threshold:", best_threshold)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_final,
        target_names=["No Breakdown", "Breakdown"],
        zero_division=0
    )
)

print("ROC-AUC:", round(roc_auc_score(y_test, y_prob), 4))
print("PR-AUC:", round(average_precision_score(y_test, y_prob), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_final))

Final Threshold: 0.5

Classification Report:
              precision    recall  f1-score   support

No Breakdown       0.99      0.99      0.99       387
   Breakdown       0.33      0.29      0.31         7

    accuracy                           0.98       394
   macro avg       0.66      0.64      0.65       394
weighted avg       0.98      0.98      0.98       394

ROC-AUC: 0.9358
PR-AUC: 0.3078

Confusion Matrix:
[[383   4]
 [  5   2]]

In [30]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight={0: 1, 1: 5},
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train_processed, y_train)

print("Random Forest trained successfully.")

Random Forest trained successfully.

In [31]:
from sklearn.model_selection import StratifiedKFold, GridSearchCV

rf_param_grid = {
    "n_estimators": [200, 300],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "class_weight": [
        {0: 1, 1: 5},
        {0: 1, 1: 10},
        {0: 1, 1: 20}
    ]
}

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

rf_grid = GridSearchCV(
    estimator=RandomForestClassifier(
        random_state=42,
        n_jobs=-1
    ),
    param_grid=rf_param_grid,
    scoring="average_precision",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

rf_grid.fit(X_train_processed, y_train)

print("Best Random Forest parameters:")
print(rf_grid.best_params_)

print("\nBest CV PR-AUC:")
print(round(rf_grid.best_score_, 4))

Fitting 5 folds for each of 72 candidates, totalling 360 fits
Best Random Forest parameters:
{'class_weight': {0: 1, 1: 10}, 'max_depth': None, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}

Best CV PR-AUC:
0.9933

In [32]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import precision_score, recall_score, f1_score

best_rf = rf_grid.best_estimator_

rf_cv_prob = cross_val_predict(
    best_rf,
    X_train_processed,
    y_train,
    cv=cv,
    method="predict_proba"
)[:, 1]

rf_threshold_results = []

for threshold in np.arange(0.05, 0.96, 0.05):

    y_pred = (rf_cv_prob >= threshold).astype(int)

    rf_threshold_results.append({
        "Threshold": round(threshold, 2),
        "Precision": round(
            precision_score(y_train, y_pred, zero_division=0), 4
        ),
        "Recall": round(
            recall_score(y_train, y_pred, zero_division=0), 4
        ),
        "F1": round(
            f1_score(y_train, y_pred, zero_division=0), 4
        )
    })

rf_threshold_df = pd.DataFrame(rf_threshold_results)

display(
    rf_threshold_df.sort_values(
        "F1",
        ascending=False
    )
)

    Threshold  Precision  Recall      F1
6        0.35     0.9286  0.9286  0.9286
5        0.30     0.8000  1.0000  0.8889
7        0.40     0.9565  0.7857  0.8627
8        0.45     0.9524  0.7143  0.8163
4        0.25     0.6829  1.0000  0.8116
9        0.50     1.0000  0.6071  0.7556
3        0.20     0.5600  1.0000  0.7179
2        0.15     0.5000  1.0000  0.6667
1        0.10     0.3944  1.0000  0.5657
10       0.55     1.0000  0.3929  0.5641
0        0.05     0.2667  1.0000  0.4211
11       0.60     1.0000  0.1429  0.2500
12       0.65     1.0000  0.0714  0.1333
13       0.70     0.0000  0.0000  0.0000
14       0.75     0.0000  0.0000  0.0000
15       0.80     0.0000  0.0000  0.0000
16       0.85     0.0000  0.0000  0.0000
17       0.90     0.0000  0.0000  0.0000
18       0.95     0.0000  0.0000  0.0000

In [33]:
rf_final_threshold = 0.35

y_prob_rf = best_rf.predict_proba(X_test_processed)[:, 1]

y_pred_rf = (y_prob_rf >= rf_final_threshold).astype(int)

print("Random Forest Final Threshold:", rf_final_threshold)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_rf,
        target_names=["No Breakdown", "Breakdown"],
        zero_division=0
    )
)

print("ROC-AUC:", round(roc_auc_score(y_test, y_prob_rf), 4))
print("PR-AUC:", round(average_precision_score(y_test, y_prob_rf), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Final Threshold: 0.35

Classification Report:
              precision    recall  f1-score   support

No Breakdown       1.00      1.00      1.00       387
   Breakdown       0.86      0.86      0.86         7

    accuracy                           0.99       394
   macro avg       0.93      0.93      0.93       394
weighted avg       0.99      0.99      0.99       394

ROC-AUC: 0.9996
PR-AUC: 0.9821

Confusion Matrix:
[[386   1]
 [  1   6]]

In [35]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    min_child_weight=2,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum(),
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train_processed, y_train)

print("XGBoost trained successfully.")

XGBoost trained successfully.

In [36]:
y_prob_xgb = xgb_model.predict_proba(X_test_processed)[:, 1]

y_pred_xgb = (y_prob_xgb >= 0.5).astype(int)

print("XGBoost Threshold: 0.50")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_xgb,
        target_names=["No Breakdown", "Breakdown"],
        zero_division=0
    )
)

print("ROC-AUC:", round(roc_auc_score(y_test, y_prob_xgb), 4))
print("PR-AUC:", round(average_precision_score(y_test, y_prob_xgb), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

XGBoost Threshold: 0.50

Classification Report:
              precision    recall  f1-score   support

No Breakdown       1.00      1.00      1.00       387
   Breakdown       0.86      0.86      0.86         7

    accuracy                           0.99       394
   macro avg       0.93      0.93      0.93       394
weighted avg       0.99      0.99      0.99       394

ROC-AUC: 0.9974
PR-AUC: 0.9286

Confusion Matrix:
[[386   1]
 [  1   6]]

In [37]:
thresholds = np.arange(0.05, 0.96, 0.05)

threshold_results = []

for threshold in thresholds:
    y_pred = (y_prob_xgb >= threshold).astype(int)

    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)

    threshold_results.append({
        "Threshold": round(threshold, 2),
        "Precision": round(precision, 4),
        "Recall": round(recall, 4),
        "F1": round(f1, 4)
    })

threshold_df_xgb = pd.DataFrame(threshold_results)

display(
    threshold_df_xgb.sort_values(
        "F1",
        ascending=False
    )
)

    Threshold  Precision  Recall      F1
16       0.85     1.0000  0.8571  0.9231
18       0.95     1.0000  0.8571  0.9231
15       0.80     1.0000  0.8571  0.9231
13       0.70     1.0000  0.8571  0.9231
14       0.75     1.0000  0.8571  0.9231
12       0.65     1.0000  0.8571  0.9231
17       0.90     1.0000  0.8571  0.9231
10       0.55     0.8571  0.8571  0.8571
9        0.50     0.8571  0.8571  0.8571
8        0.45     0.8571  0.8571  0.8571
3        0.20     0.8571  0.8571  0.8571
6        0.35     0.8571  0.8571  0.8571
5        0.30     0.8571  0.8571  0.8571
4        0.25     0.8571  0.8571  0.8571
7        0.40     0.8571  0.8571  0.8571
11       0.60     0.8571  0.8571  0.8571
1        0.10     0.7500  0.8571  0.8000
2        0.15     0.7500  0.8571  0.8000
0        0.05     0.5455  0.8571  0.6667

In [38]:
xgb_final_threshold = 0.70

y_pred_xgb_final = (y_prob_xgb >= xgb_final_threshold).astype(int)

print("XGBoost Final Threshold:", xgb_final_threshold)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_xgb_final,
        target_names=["No Breakdown", "Breakdown"],
        zero_division=0
    )
)

print("ROC-AUC:", round(roc_auc_score(y_test, y_prob_xgb), 4))
print("PR-AUC:", round(average_precision_score(y_test, y_prob_xgb), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb_final))

XGBoost Final Threshold: 0.7

Classification Report:
              precision    recall  f1-score   support

No Breakdown       1.00      1.00      1.00       387
   Breakdown       1.00      0.86      0.92         7

    accuracy                           1.00       394
   macro avg       1.00      0.93      0.96       394
weighted avg       1.00      1.00      1.00       394

ROC-AUC: 0.9974
PR-AUC: 0.9286

Confusion Matrix:
[[387   0]
 [  1   6]]

In [39]:
comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],
    "Threshold": [
        0.50,
        0.35,
        0.70
    ],
    "Breakdown_F1": [
        0.31,
        0.86,
        0.92
    ],
    "Breakdown_Recall": [
        0.29,
        0.86,
        0.86
    ],
    "ROC_AUC": [
        0.9358,
        0.9996,
        0.9974
    ],
    "PR_AUC": [
        0.3078,
        0.9821,
        0.9286
    ]
})

display(comparison)

,Model,Threshold,Breakdown_F1,Breakdown_Recall,ROC_AUC,PR_AUC
0,Logistic Regression,0.50,0.31,0.29,0.9358,0.3078
1,Random Forest,0.35,0.86,0.86,0.9996,0.9821
2,XGBoost,0.70,0.92,0.86,0.9974,0.9286

In [40]:
import joblib

model_package = {
    "model": xgb_model,
    "preprocessor": preprocessor,
    "threshold": 0.70,
    "feature_columns": X.columns.tolist()
}

joblib.dump(model_package, "vehicle_breakdown_model.pkl")

print("Model package saved successfully.")

Model package saved successfully.